# BigMart Sales Prediction

Dataset link: https://www.kaggle.com/brijbhushannanda1979/bigmart-sales-data

In [1]:
# Loading essential libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Importing the dataset as training and testing data.

train= pd.read_csv(r'C:\Users\user\Desktop\Springboard\Curriculum Projects\Big Mart Sales Prediction\train.csv')
test= pd.read_csv(r'C:\Users\user\Desktop\Springboard\Curriculum Projects\Big Mart Sales Prediction\test.csv')

In [3]:
# Combining train and test into one file in order to do some data cleaning

train['source']='train'
test['source']= 'test'

df= pd.concat([train, test], ignore_index= True, sort=False)
print(train.shape, test.shape, df.shape)

(8523, 13) (5681, 12) (14204, 13)


In [4]:
df.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales source  
0  Supermarket Type1          3735.1380  train  
1  Supermarket Type2           443.4228  train  
2  Supermarket Type1          2097.2700  train  
3      Grocery Store           732.3800  train  
4  Supermarket Type1           994.7052  train

In [5]:
# Statistical Data Analysis

df.describe()

Item_Weight  Item_Visibility      Item_MRP  Outlet_Establishment_Year  \
count  11765.000000     14204.000000  14204.000000               14204.000000   
mean      12.792854         0.065953    141.004977                1997.830681   
std        4.652502         0.051459     62.086938                   8.371664   
min        4.555000         0.000000     31.290000                1985.000000   
25%        8.710000         0.027036     94.012000                1987.000000   
50%       12.600000         0.054021    142.247000                1999.000000   
75%       16.750000         0.094037    185.855600                2004.000000   
max       21.350000         0.328391    266.888400                2009.000000   

       Item_Outlet_Sales  
count        8523.000000  
mean         2181.288914  
std          1706.499616  
min            33.290000  
25%           834.247400  
50%          1794.331000  
75%          3101.296400  
max         13086.964800

In [6]:
# Checking if any null values present in the columns of independent variables.

df.apply(lambda x: sum(x.isnull()))

Item_Identifier                 0
Item_Weight                  2439
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales            5681
source                          0
dtype: int64

In [7]:
# Filling missing values with thye mean values of thye columns where ever possible and in case of categorical variables subsituting the values of highest frequency

df.Item_Weight= df.Item_Weight.fillna(df.Item_Weight.mean())
df.Outlet_Size= df.Outlet_Size.fillna('Medium')
df.Item_Outlet_Sales= df.Item_Outlet_Sales.fillna(df.Item_Outlet_Sales.mean())

In [8]:
# Post filling the missing value check

df.apply(lambda x: sum(x.isnull()))

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
source                       0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14204 entries, 0 to 14203
Data columns (total 13 columns):
Item_Identifier              14204 non-null object
Item_Weight                  14204 non-null float64
Item_Fat_Content             14204 non-null object
Item_Visibility              14204 non-null float64
Item_Type                    14204 non-null object
Item_MRP                     14204 non-null float64
Outlet_Identifier            14204 non-null object
Outlet_Establishment_Year    14204 non-null int64
Outlet_Size                  14204 non-null object
Outlet_Location_Type         14204 non-null object
Outlet_Type                  14204 non-null object
Item_Outlet_Sales            14204 non-null float64
source                       14204 non-null object
dtypes: float64(4), int64(1), object(8)
memory usage: 1.4+ MB


In [10]:
# Item_Type combining

df['Item_Identifier'].value_counts()
df['Item_Type_Combined']= df['Item_Identifier'].apply(lambda x: x[0:2])
df['Item_Type_Combined'] = df['Item_Type_Combined'].map({'FD':'Food',
                                                         'NC':'Non-Consumable',
                                                         'DR':'Drinks'})
df['Item_Type_Combined'].value_counts()

Food              10201
Non-Consumable     2686
Drinks             1317
Name: Item_Type_Combined, dtype: int64

In [11]:
# Numerical and One-Hot Encoding of Categorical Variables 

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le= LabelEncoder()

# Creating new variable for outlet

df['Outlet']= le.fit_transform(df['Outlet_Identifier'])
var_mod= ['Item_Fat_Content','Outlet_Location_Type', 'Outlet_Size','Outlet_Type', 'Item_Type_Combined', 'Outlet']

for i in var_mod:
    df[i]= le.fit_transform(df[i])
    

In [12]:
# One Hot Encoding

df= pd.get_dummies(df, columns= ['Item_Fat_Content','Outlet_Location_Type', 'Outlet_Size','Outlet_Type', 'Item_Type_Combined', 'Outlet'])
df.head()

Item_Identifier  Item_Weight  Item_Visibility              Item_Type  \
0           FDA15         9.30         0.016047                  Dairy   
1           DRC01         5.92         0.019278            Soft Drinks   
2           FDN15        17.50         0.016760                   Meat   
3           FDX07        19.20         0.000000  Fruits and Vegetables   
4           NCD19         8.93         0.000000              Household   

   Item_MRP Outlet_Identifier  Outlet_Establishment_Year  Item_Outlet_Sales  \
0  249.8092            OUT049                       1999          3735.1380   
1   48.2692            OUT018                       2009           443.4228   
2  141.6180            OUT049                       1999          2097.2700   
3  182.0950            OUT010                       1998           732.3800   
4   53.8614            OUT013                       1987           994.7052   

  source  Item_Fat_Content_0  ...  Outlet_0  Outlet_1  Outlet_2  Outlet_3  \
0  train                   0  ...         0         0         0         0   
1  train                   0  ...         0         0         0         1   
2  train                   0  ...         0         0         0         0   
3  train                   0  ...         1         0         0         0   
4  train                   0  ...         0         1         0         0   

   Outlet_4  Outlet_5  Outlet_6  Outlet_7  Outlet_8  Outlet_9  
0         0         0         0         0         0         1  
1         0         0         0         0         0         0  
2         0         0         0         0         0         1  
3         0         0         0         0         0         0  
4         0         0         0         0         0         0  

[5 rows x 37 columns]

In [13]:
# Exporting the modified data into new .csv files
import warnings
warnings.filterwarnings('ignore')

# Dropping unneccessary columns
df.drop(['Item_Type', 'Outlet_Establishment_Year'], axis=1, inplace= True)

# Dividing the combined data into train and test data again

train= df.loc[df['source']=='train']
test= df.loc[df['source']== 'test']

# Dropping unneccessary Columns again

test.drop(['Item_Outlet_Sales', 'source'], axis=1, inplace= True)
train.drop(['source'], axis=1, inplace= True)

#Exporting files as modified versions:

train.to_csv('training_data_modified.csv', index= False)
test.to_csv('testing_data_modified.csv', index= False)

## Creating Models for Sales Evaluation

In [14]:
# Reading Modified data
train2= pd.read_csv('training_data_modified.csv')
test2= pd.read_csv('testing_data_modified.csv')

In [15]:
train2.head()

Item_Identifier  Item_Weight  Item_Visibility  Item_MRP Outlet_Identifier  \
0           FDA15         9.30         0.016047  249.8092            OUT049   
1           DRC01         5.92         0.019278   48.2692            OUT018   
2           FDN15        17.50         0.016760  141.6180            OUT049   
3           FDX07        19.20         0.000000  182.0950            OUT010   
4           NCD19         8.93         0.000000   53.8614            OUT013   

   Item_Outlet_Sales  Item_Fat_Content_0  Item_Fat_Content_1  \
0          3735.1380                   0                   1   
1           443.4228                   0                   0   
2          2097.2700                   0                   1   
3           732.3800                   0                   0   
4           994.7052                   0                   1   

   Item_Fat_Content_2  Item_Fat_Content_3  ...  Outlet_0  Outlet_1  Outlet_2  \
0                   0                   0  ...         0         0         0   
1                   1                   0  ...         0         0         0   
2                   0                   0  ...         0         0         0   
3                   1                   0  ...         1         0         0   
4                   0                   0  ...         0         1         0   

   Outlet_3  Outlet_4  Outlet_5  Outlet_6  Outlet_7  Outlet_8  Outlet_9  
0         0         0         0         0         0         0         1  
1         1         0         0         0         0         0         0  
2         0         0         0         0         0         0         1  
3         0         0         0         0         0         0         0  
4         0         0         0         0         0         0         0  

[5 rows x 34 columns]

In [16]:
# Initialising the independent and dependent variables of Training dataset

X_train = train2.drop(['Item_Outlet_Sales', 'Outlet_Identifier','Item_Identifier'], axis=1)
y_train= train2.Item_Outlet_Sales

In [17]:
# Performing futher Data cleaning

X_test= test2.drop(['Outlet_Identifier', 'Item_Identifier'], axis=1)

X_train.head()

Item_Weight  Item_Visibility  Item_MRP  Item_Fat_Content_0  \
0         9.30         0.016047  249.8092                   0   
1         5.92         0.019278   48.2692                   0   
2        17.50         0.016760  141.6180                   0   
3        19.20         0.000000  182.0950                   0   
4         8.93         0.000000   53.8614                   0   

   Item_Fat_Content_1  Item_Fat_Content_2  Item_Fat_Content_3  \
0                   1                   0                   0   
1                   0                   1                   0   
2                   1                   0                   0   
3                   0                   1                   0   
4                   1                   0                   0   

   Item_Fat_Content_4  Outlet_Location_Type_0  Outlet_Location_Type_1  ...  \
0                   0                       1                       0  ...   
1                   0                       0                       0  ...   
2                   0                       1                       0  ...   
3                   0                       0                       0  ...   
4                   0                       0                       0  ...   

   Outlet_0  Outlet_1  Outlet_2  Outlet_3  Outlet_4  Outlet_5  Outlet_6  \
0         0         0         0         0         0         0         0   
1         0         0         0         1         0         0         0   
2         0         0         0         0         0         0         0   
3         1         0         0         0         0         0         0   
4         0         1         0         0         0         0         0   

   Outlet_7  Outlet_8  Outlet_9  
0         0         0         1  
1         0         0         0  
2         0         0         1  
3         0         0         0  
4         0         0         0  

[5 rows x 31 columns]

In [18]:
X_test.head()

Item_Weight  Item_Visibility  Item_MRP  Item_Fat_Content_0  \
0    20.750000         0.007565  107.8622                   0   
1     8.300000         0.038428   87.3198                   0   
2    14.600000         0.099575  241.7538                   0   
3     7.315000         0.015388  155.0340                   0   
4    12.792854         0.118599  234.2300                   0   

   Item_Fat_Content_1  Item_Fat_Content_2  Item_Fat_Content_3  \
0                   1                   0                   0   
1                   0                   0                   0   
2                   1                   0                   0   
3                   1                   0                   0   
4                   0                   1                   0   

   Item_Fat_Content_4  Outlet_Location_Type_0  Outlet_Location_Type_1  ...  \
0                   0                       1                       0  ...   
1                   1                       0                       1  ...   
2                   0                       0                       0  ...   
3                   0                       0                       1  ...   
4                   0                       0                       0  ...   

   Outlet_0  Outlet_1  Outlet_2  Outlet_3  Outlet_4  Outlet_5  Outlet_6  \
0         0         0         0         0         0         0         0   
1         0         0         1         0         0         0         0   
2         1         0         0         0         0         0         0   
3         0         0         1         0         0         0         0   
4         0         0         0         0         0         1         0   

   Outlet_7  Outlet_8  Outlet_9  
0         0         0         1  
1         0         0         0  
2         0         0         0  
3         0         0         0  
4         0         0         0  

[5 rows x 31 columns]

In [19]:
y_train.head()

0    3735.1380
1     443.4228
2    2097.2700
3     732.3800
4     994.7052
Name: Item_Outlet_Sales, dtype: float64

### Linear Regression Model

In [20]:
from sklearn.linear_model import LinearRegression

regressor= LinearRegression(n_jobs=1)
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
# Predicting the test set results

y_pred= regressor.predict(X_test)
y_pred

array([1848.53604783, 1472.81670435, 1875.65285894, ..., 1809.18796433,
       3565.6645235 , 1267.46171871])

In [22]:
import warnings
warnings.filterwarnings('ignore')

# Measuring Accuracy

from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn import metrics

In [23]:
# Linear Regression accuracy score

lr_accuracy= round(regressor.score(X_train, y_train)*100,2)
lr_accuracy

56.36

In [24]:
# Linear Regression R^2 score

r2_score(y_train, regressor.predict(X_train))

0.563589277727048

In [25]:
import warnings
warnings.filterwarnings('ignore')

# Performing Cross Validation

cv_score= cross_val_score(regressor, X_train, y_train, cv=5)

print(np.sqrt(np.abs(cv_score)))

[0.75571633 0.74509312 0.73995267 0.75255581 0.75171429]


In [26]:
print("RMSE : %.4g" %np.sqrt(metrics.mean_squared_error(y_train, regressor.predict(X_train))))


RMSE : 1127


In [27]:
submission= pd.DataFrame({
    'Item_Identifier':test2['Item_Identifier'],
    'Outlet_Identifier': test2['Outlet_Identifier'],
    'Item_Outlet_Sales': y_pred
}, columns=['Item_Identifier', 'Outlet_Identifier','Item_Outlet_Sales'])

In [28]:
submission.to_csv('submission1.csv', index= False)

## Random Forest Model

In [29]:
# fitting Random Forest Regression to the dataset

from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(n_estimators=100, max_depth=6, min_samples_leaf=50, n_jobs=4)
regressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=6, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=50,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=4, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [30]:
y_pred= regressor.predict(X_test)
y_pred

array([1654.61263493, 1370.3804547 ,  589.81104428, ..., 1945.00545037,
       3735.29961682, 1294.57681372])

In [31]:
# Random Forest Accuracy Score

rf_accuracy= round(regressor.score(X_train, y_train)*100,2)
rf_accuracy

61.25

In [32]:
# Random Forest R^2 score

r2_score(y_train, regressor.predict(X_train))

0.6125302216119265

In [33]:
cv_score= cross_val_score(regressor, X_train, y_train, cv=5)
print(np.sqrt(np.abs(cv_score)))

[0.7795844  0.76591328 0.7585574  0.78039753 0.77894336]


In [34]:
print("RMSE : %.4g" % np.sqrt(metrics.mean_squared_error(y_train, regressor.predict(X_train))))

RMSE : 1062


In [35]:
submission= pd.DataFrame({
    'Item_Identifier':test2['Item_Identifier'],
    'Outlet_Identifier': test2['Outlet_Identifier'],
    'Item_Outlet_Sales': y_pred
}, columns=['Item_Identifier', 'Outlet_Identifier','Item_Outlet_Sales'])

In [36]:
submission.to_csv('submission2.csv', index= False)

## Decision Tree Model

In [37]:
# Fitting Decision Tree Regression to the dataset

from sklearn.tree import DecisionTreeRegressor
regressor= DecisionTreeRegressor(max_depth=15, min_samples_leaf=300)
regressor.fit(X_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=15,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=300, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [38]:
# Predicting the test set results
y_pred= regressor.predict(X_test)
y_pred

array([1673.98398729, 1349.51290433,  471.30684669, ..., 1892.06614452,
       3805.94860417, 1349.51290433])

In [39]:
tree_accuracy= round(regressor.score(X_train, y_train)*100,2)
tree_accuracy

58.84

In [40]:
r2_score(y_train, regressor.predict(X_train))

0.5884050821570486

In [41]:
import warnings
warnings.filterwarnings('ignore')
cv_score= cross_val_score(regressor, X_train, y_train, cv=5)
print(np.sqrt(np.abs(cv_score)))

[0.76166126 0.74999795 0.72145219 0.75916104 0.75750393]


In [42]:
print("RMSE : %.4g" %np.sqrt(metrics.mean_squared_error(y_train, regressor.predict(X_train))))

RMSE : 1095


In [43]:
submission= pd.DataFrame({
    'Item_Identifier':test2['Item_Identifier'],
    'Outlet_Identifier': test2['Outlet_Identifier'],
    'Item_Outlet_Sales': y_pred
}, columns=['Item_Identifier', 'Outlet_Identifier','Item_Outlet_Sales'])

In [44]:
submission.to_csv('submission3.csv', index= False)